### ISSUE TITLE
HA crashes when host is unreachable

### ISSUE THREAD

**Issue by Cryotize** [OStrama/weishaupt_modbus#7]
**Describe the bug**
If the host (pump or whatever) is unreachable for whatever reason, it crashes my HA instance. I had to remove the integration via terminal in order to get HA working again. I don't know if this an error by this integration, or if HA should disable the integration by itself when it detects this kind of error.

**Steps to reproduce the error**
Have the integration setup in HA, unplug your host so that it is unreachable, wait for HA to crash.

**Expected behavior**
HA should continue working, even when the integration is failing.

**Logs**
```bash
homeassistant  | 2024-10-16 11:34:24.907 ERROR (MainThread) [pymodbus.logging] Connection to (10.10.11.101, 502) failed: timed out
homeassistant  | 2024-10-16 11:34:24.975 ERROR (MainThread) [pymodbus.logging] Connection to (10.10.11.101, 502) failed: [Errno 113] Host is unreachable
homeassistant  | 2024-10-16 11:34:12.617 ERROR (MainThread) [homeassistant.components.sensor] weishaupt_wbb: Error on device update!
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 724, in _async_add_entity
homeassistant  |     await entity.async_device_update(warning=False)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
homeassistant  |     await self.async_update()
homeassistant  |   File "/config/custom_components/weishaupt_wbb/entities.py", line 156, in async_update
homeassistant  |     self._attr_native_value = self.translateVal
homeassistant  |                               ^^^^^^^^^^^^^^^^^
homeassistant  |   File "/config/custom_components/weishaupt_wbb/entities.py", line 171, in translateVal
homeassistant  |     val_x = self.calcTemperature(mbo_x.value) / 10
homeassistant  |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
homeassistant  | TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

**Comment by MadOne** [comment]
You can specifiy the timeout for a modbus connection / request:

modbusobject.py line 31:
self._ModbusClient = ModbusClient(host=self._ip, port=self._port, timeout=1)

But the problem still exists, because the integration does this for all entities (85 in my case)

I think the best approach would be to create one object that periodically pulls all modbus values.
Looks like the update coordinator is what is designed for this purpose.
https://developers.home-assistant.io/docs/integration_fetching_data/

**Comment by thetschulian** [comment]
Hey there, thanks for this great addon. 
I can confirm this error with a WBB20.
I have the WBB20 in my checkmk monitoring, everytime the modbus tcp port is unreachable, the HA is not responding.

**Comment by MadOne** [comment]
Maybe something like this?

https://github.com/MadOne/weishaupt_modbus/blob/test/custom_components/weishaupt_modbus/heatpump.py

**Comment by OStrama** [comment]
Thanks for the tips and ideas! 

Who calls the poll method?

(I also got some hints from the ModbusTCPClient developers to use the async methods. I think this would be the preferred way but I have to understand how to use them. )

**Comment by MadOne** [comment]
This is just a small proof if concept. According to the ha developer docs s update coordinator is designed to poll all values and update the entitys.

Just ket my know if you want me to further  check this approach. I think this has several advanteges to not open a new Connection for every value.

Anyways switching to async is surely good. The integration will still get stuck in timeouts but not block the home Assistent main "thread". 

I think the best solution would be a combination of both.

**Comment by MadOne** [comment]
I managed to switch to the async modbus client:
https://github.com/MadOne/weishaupt_modbus/commit/e1b531ce3255e932bcd0fe12cfa749980e1b6dc4

The HA Container automatically reformats the edited files on save. So there is some reformating.
I think you can pull this commit if you are ok with that reformating. Otherwise it should be pretty easy to see what has to be changed.

**Comment by OStrama** [comment]
Thanks! Looks great. I'll pull the commit and integrate it. 

I assume you mean "Wärmeleisrtung" when you talk aboput thew calculated sensor. What's the problem with it? 

BTW: Is it possible to open a repository so that more than one person can work on it? In my opinion it would make sense to work together on one code base...

**Comment by OStrama** [comment]
... reformatting is no problem ;-). It's my 1st Python project after many years C/C++, so maybe my formatting is not the typical Python one...

**Comment by MadOne** [comment]
> Thanks! Looks great. I'll pull the commit and integrate it.
> 
> I assume you mean "Wärmeleisrtung" when you talk aboput thew calculated sensor. What's the problem with it?
> 
> BTW: Is it possible to open a repository so that more than one person can work on it? In my opinion it would make sense to work together on one code base...

Yes "Wärmeleistung" was the problem. I didnt have time to to check what the problem is yet. I think there are some async and awaits missing.

I would really like to work with you on this integration. But be aware i am no programmer. I am a mechanical engineer and only doing this as a hobby. Im pretty new to python too. 


> ... reformatting is no problem ;-). It's my 1st Python project after many years C/C++, so maybe my formatting is not the typical Python one...

The problem is, it makes pull requests and diffs more complicated to read. I am using the HomAssistant dev container, witch is verry convinient by the way. It uses RUFF for lintig and code formating. Maybe we could agree on using that?

If you still want to work with me you can add me under settings -> Collaborators.

**Comment by OStrama** [comment]
Yes, of course! Working together would be great! I added you as collaborator, so please feel free to contribute to this repo.
I also changed to the Devcontainer and RUFF, so the diffs should be easy from now on..

**Comment by OStrama** [comment]
I changed modbus calls to async. Made some debugging (@property.setter does not work async etc..) and now it seems to run.

However, I get a lot of "Failed to connect". Any idea to avoid them?

**Comment by MadOne** [comment]
I also have them. I added some warnings myself while Debugging. Not sure if this is my debuging or not. Had no spare time today, hope i can look into tomorrow.

**Comment by thetschulian** [comment]
side info:
my heatpump becomes unavailable for a couple of minutes everytime e-heizung 1 changes from EIN to AUS. 
I contacted the support already since I guess its a bug in the firmware

**Comment by OStrama** [comment]
> side info: my heatpump becomes unavailable for a couple of minutes everytime e-heizung 1 changes from EIN to AUS. I contacted the support already since I guess its a bug in the firmware

interesting, I'll check it by manually switching on E1...

**Comment by OStrama** [comment]
It was not only the warnings, I also have gaps in the data because the sensors become unavailable from time to time due to the connection errors.
However, I made a test in reading sensor values according to https://developers.home-assistant.io/docs/integration_fetching_data/. 
In principle this works without errors and gaps. But: I only get the data from the sensors up to statistics. The last sensors in the list are missing. If I do not read them from Modbus but only return the addresses, I get the values. If I change the order, always the last few sensors are missing. So it seems to be a timing problem. Any idea how to get rid of it?
If there's a solution I'll reconfigure the whole stuff in that way..

**Comment by MadOne** [comment]
Maybe many connections in a short time?

**Comment by OStrama** [comment]
Hmm, I open the Client at the beginning and then I start reading one register after the other. I also tried open/close the connection for every request. Both had no influence. I have the impression that the coordinator stops after a certain time?

**Comment by MadOne** [comment]
We are loosing a lot of info with the try except statements. I think we should do some proper error handling. This will help debug alot. While implementing the async client i completely removed them.

**Comment by MadOne** [comment]
Maybe it is running into the [timeout](https://github.com/OStrama/weishaupt_modbus/blob/f42d2517d6a27b718aac15f19da7dbe16d86122c/custom_components/weishaupt_modbus/entities.py#L145)?

**Comment by MadOne** [comment]
Fixed the missing sensors with [this](https://github.com/OStrama/weishaupt_modbus/commit/ad53a49345aead05ca403d8962e7e38b4d17a42b)

**Comment by thetschulian** [comment]
Good Morning, i added the WBB20 modbus tcp port 502 to my checkmk monitoring. 
I disabled the HA Integration for my WBB20 and since that moment I had no more tcp timeouts on port 502. therefore I guess, the HA integration is "flooding" the WBB and than the tcp stack may crashes and after a couple of time a daemon on the wbb restarts the tcp stack 

maybe it was a coincidence? I will look at this the next hours / days and report back if needed. 
i am not sure and I cannot proof it yet. is there a way to look deeper in the logs of the wbb on the local control panel or can i "export" them somehow to a usb device because my wbb20 has a usb-a port.

**Comment by MadOne** [comment]
The modbus structure and requests will be drasticly changed in the new version. 

At the moment every 30 seconds a lot if invalid requests happen. We want to filter that ones so they only happen once on initialisation. 

I have no clue on how to debug the heatpump itself.

**Comment by thetschulian** [comment]
> The modbus structure and requests will be drasticly changed in the new version.
> 
> At the moment every 30 seconds a lot if invalid requests happen. We want to filter that ones so they only happen once on initialisation.
> 
> I have no clue on how to debug the heatpump itself.

great, thank you :)  today a weishaupt technician is in the house. I will ask him for debug logs etc.

**Comment by thetschulian** [comment]
Good Morning, yesterday the technician installed a new firmware. since that I have more less timeouts on port 502 or via ping even with HA Integration enabled  as with the old firmware. 
but I still face small timeouts 
![image](https://github.com/user-attachments/assets/78114453-48e4-43d0-96a9-549478fb4484)

**Comment by OStrama** [comment]
What version do you use currently? Could you perhaps test the 0.0.8pre2 (see readme before..)

**Comment by MadOne** [comment]
Now you got me. I will setup a monitoring too. 

Will will have to compare to a period without a running modbus integration.

Do you have any progress on debugging the heatpump itself?

**Comment by MadOne** [comment]
What frequency do you use to Monitor the modbus port?

**Comment by thetschulian** [comment]
Hey, my checkmk is checking it by default every 60 seconds. 
If u are interested in a small checkmk crash course let me know how to contact you. 

> Do you have any progress on debugging the heatpump itself?
not yet, I will have a look at it tommorow again


I try to install the pre release

**Comment by OStrama** [comment]
> What frequency do you use to Monitor the modbus port?

The integration polls every 30 seconds

class MyCoordinator(DataUpdateCoordinator):
    """My custom coordinator."""

    def __init__(self, hass, my_api, modbusitems):
        """Initialize my coordinator."""
        super().__init__(
            …..
            update_interval=timedelta(seconds=30)

**Comment by MadOne** [comment]
> Hey, my checkmk is checking it by default every 60 seconds. If u are interested in a small checkmk crash course let me know how to contact you.
> 
> > Do you have any progress on debugging the heatpump itself?
> 
> not yet, I will have a look at it tommorow again
> 
> I try to install the pre release - currently I am at the latest major release ( ... 7 ) okay I am running on pre2 now.
> 
> do you guys have a discord channel for easier communication?

I just created one:
https://discord.gg/gXE55MhH

**Comment by MadOne** [comment]
![Bildschirmfoto vom 2024-10-28 18-17-05](https://github.com/user-attachments/assets/335017db-756d-402e-adbc-5e8de35af039)
This is with 0.0.5
I now upgraded to 0.0.8pre and will monitor the next 24 hours.

**Comment by OStrama** [comment]
What's the status of this test. Can we close the issue completely? 
(Crashes do not happen anymore when disconnected..)

**Comment by MadOne** [comment]
I will close this issue. The original issue is resolved. I tested right now.
I havent had any timeouts the last days.
If anyone faces timeouts we should create a new issue.
